mysite2/mysite2/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.views.static import serve
from app01.views import depart, user, pretty, admin, account, task, order, chart, upload, city


urlpatterns = [
    # path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('depart/multi/', depart.depart_multi),
    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/form/', user.user_form),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),
    # 靓号管理
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),
    # 管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),
    # 登录
    path('login/', account.login),
    # 注销
    path('logout/', account.logout),
    path('image/code/', account.image_code),
    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),
    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    # 上传文件
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/modal/form/', upload.upload_modal_form),
    # 城市管理
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),

]

mysite2/app01/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username

class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name='部门', max_length=32)

    def __str__(self):
        return self.title

class UserInfo(models.Model):
    ''' 员工表 '''
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")
    depart = models.ForeignKey(verbose_name="所属部门", to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)

class PrettyNum(models.Model):
    ''' 靓号 '''
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)
    level_choices = (
        (1, "一级"),
        (2, "二级"),
        (3, "三级"),
        (4, "四级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (0, "未占用"),
        (1, "已占用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=0)

    # def __str__(self):
    #     return self.

class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="商品名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")
    status_choice = (
        (1, "待支付"),
        (2, "已支付")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choice, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", to_field="id", on_delete=models.CASCADE)

class Boss(models.Model):
    """ 上传文件表 """
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="图片路径", max_length=128)

class City(models.Model):
    """ 上传城市文件表 """
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    img = models.FileField(verbose_name="logo", max_length=128, upload_to='city/')

mysite2/app01/views/account.py
from django.shortcuts import render, redirect, HttpResponse
from django import forms
from app01 import models
from app01.utils.encrypt import md5
from app01.utils.code import check_code
from io import BytesIO

class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,  # 不能为空，必填
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )

    def clean_password(self):
        pwd = self.cleaned_data["password"]
        return md5(pwd)


def login(request):
    """ 登录"""

    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        # .pop()从cleaned_data中，把code拿出来，不是获取（也就是拿出来后，cleaned_data里就没有code了）
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')
        if code.upper() != user_input_code.upper():  # .upper()小写字母换成大写字母
            form.add_error("code", "验证码错误")
            return render(request, "login.html", {"form": form})
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")  # 错误显示在密码下面
            return render(request, "login.html", {"form": form})
        request.session["info"] = {"id": admin_object.id, "username": admin_object.username}
        request.session.set_expiry(60 * 60 * 24 * 7)  # 保存七天
        return redirect("/admin/list/")

    return render(request, 'login.html', {"form": form})

def image_code(request):
    """ 生成图片验证码"""

    img, code_string = check_code()
    # 写入到自己的session中（以便于后续获取验证码在进行校验）
    request.session['image_code'] = code_string
    # 给session设置一个60秒超时
    request.session.set_expiry(60)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    """ 注销"""

    request.session.clear()

    return redirect("/login/")

mysite2/app01/views/admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminForm, AdminEditForm, AdminResetForm


def admin_list(request):
    # 搜索
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["username__contains"] = search_data
    queryset = models.Admin.objects.filter(**data_dict)
    # 分页
    page_object = Pagination(request, queryset)

    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
        "search_data": search_data
    }
    return render(request, "admin_list.html", context)


def admin_add(request):
    title = "新建管理员"
    if request.method == "GET":
        form = AdminForm()
        return render(request, "change.html", {"form": form, "title": title})
    form = AdminForm(data=request.POST)
    if form.is_valid():
        # form.cleaned_data # 验证通过后所有的数据
        form.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {"form": form, "title": title})


def admin_edit(request, nid):
    """ 编辑管理员"""

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect("/admin/list/")

    title = "编辑管理员"
    if request.method == "GET":
        form = AdminEditForm(instance=row_object)
        return render(request, "change.html", {"form": form, "title": title})
    form = AdminEditForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list")
    return render(request, "change.html", {"form": form, "title": title})


def admin_delete(request, nid):
    """ 删除管理员"""

    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list")

def admin_reset(request, nid):
    """ 重置密码"""

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect("/admin/list/")

    title = "重置密码--{}".format(row_object.username)
    if request.method == "GET":
        form = AdminResetForm()
        return render(request, "change.html", {"form": form, "title": title})
    form = AdminResetForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {"form": form, "title": title})

mysite2/app01/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse
def chart_list(request):
    return render(request, "chart_list.html")

def chart_bar(request):
    """ 构造柱状图的数据 """
    legend = ["销量", "变量"]
    series_list = [
        {
            "name": '销量',
            "type": 'bar',
            "data": [20, 40, 50, 30, 30, 50]
        },
        {
            "name": '变量',
            "type": 'bar',
            "data": [50, 70, 20, 35, 80, 50]
        }
    ]
    x_axis = ['一月', '二月', '三月', '四月', '五月', '六月']
    result = {
        "status": True,
        "data": {
            "legend": legend,
            "series": series_list,
            "x_axis": x_axis,
        }
    }
    return JsonResponse(result)

def chart_pie(request):
    """ 构造饼图的数据 """
    db_data_list = [
        {"value": 2048, "name": 'IT部门'},
        {"value": 1735, "name": '研发部'},
        {"value": 580, "name": '新媒体'},
    ]
    result = {
        "status": True,
        "data": db_data_list
    }
    return JsonResponse(result)

mysite2/app01/views/city.py
from django.shortcuts import render, redirect
from app01 import models
from django import forms
def city_list(request):
    queryset = models.City.objects.all()
    return render(request, "city_list.html", {"queryset": queryset})


class UpModalForm(forms.ModelForm):
    class Meta:
        model = models.City
        fields = "__all__"


def city_add(request):
    title = "新建城市"
    if request.method == "GET":
        form = UpModalForm()
        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = UpModalForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()  # 对于文件：自动保存; 字段 + 上传路径写入到数据库
        return redirect("/city/list/")
    return render(request, 'upload_form.html', {"form": form, "title": title})

mysite2/app01/views/depart.py
from django.shortcuts import render, redirect
from app01 import models
from openpyxl import load_workbook

def depart_list(request):
    # 部门列表
    # if request.method == "GET":
    queryset = models.Department.objects.all()
    return render(request, "depart_list.html", {"queryset": queryset})

    # return render(request, "depart_add.html")

def depart_add(request):
    if request.method == "GET":
        return render(request, "depart_add.html")
    title = request.POST.get("a")
    models.Department.objects.create(title=title)
    return redirect("/depart/list/")

def depart_delete(request):
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")

def depart_edit(request, nid):
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"row_object": row_object})
    title = request.POST.get("b")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")

def depart_multi(request):
    # 1.获取用户上传的文件对象
    file_object = request.FILES.get("exc")

    # 2.对象传递给openpyxl,由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):  # 从文件的第二行开始读取
        text = row[0].value
        exists = models.Department.objects.filter(title=text).exists()
        if not exists:
            models.Department.objects.create(title=text)

    return redirect("/depart/list/")

mysite2/app01/views/order.py
import random
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from app01.utils.form import OrderModelForm
from app01 import models
from app01.utils.pagination import Pagination
from datetime import datetime

def order_list(request):
    queryset = models.Order.objects.all().order_by('-id')
    page_object = Pagination(request, queryset)
    form = OrderModelForm()
    context = {
        "form": form,
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html()  # 生成页码
    }
    return render(request, "order_list.html", context)

@csrf_exempt
def order_add(request):
    """ 新建订单 （Ajax请求）"""
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
        form.instance.admin_id = request.session["info"]["id"]
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

def order_delete(request):
    uid = request.GET.get("uid")
    exists = models.Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({"status": False, "error": "数据不存在，删除失败。"})
    models.Order.objects.filter(id=uid).delete()
    return JsonResponse({"status": True})

def order_detail(request):
    """ 根据id获取当前行并填入input框"""
    # 方式一
    # uid = request.GET.get("uid")
    # row_object = models.Order.objects.filter(id=uid).first()
    # if not row_object:
    #     return JsonResponse({"status": False, "error": "数据不存在。"})
    # result = {
    #     "status": True,
    #     "data":{
    #         "title": row_object.title,
    #         "price": row_object.price,
    #         "status": row_object.status,
    #     }
    # }
    # return JsonResponse(result)

    # 方式二
    uid = request.GET.get("uid")
    row_dict = models.Order.objects.filter(id=uid).values("title", "price", "status").first()
    if not row_dict:
        return JsonResponse({"status": False, "error": "数据不存在。"})
    result = {
        "status": True,
        "data": row_dict
    }
    print(row_dict)
    return JsonResponse(result)
@ csrf_exempt
def order_edit(request):
    """ 编辑"""
    uid = request.GET.get("uid")
    row_object = models.Order.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, "tips": "数据不存在。"})
    form = OrderModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

mysite2/app01/views/task.py
import json

from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt


def task_list(request):
    return render(request, "task_list.html")

@csrf_exempt
def task_ajax(request):
    print(request.GET)
    print(request.POST)
    data_dict = {"status": True, "data": [11, 22, 33]}
    return HttpResponse(json.dumps(data_dict))
    # return JsonResponse(data_dict)

mysite2/app01/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <!-- Single button -->
    <div class="clearfix" style="margin-bottom: 10px">
        <a class="btn btn-warning" href="/admin/add/" target="_blank">
            新建管理员</a>
        <div style="float: right;width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Search for..."
                           value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                        </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">管理员列表</div>
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>管理员name</th>
                <th>密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
            <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.username }}</td>
                <td>******</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/admin/{{ item.id }}/edit/">编辑</a>
                    <a class="btn btn-danger btn-xs" href="/admin/{{ item.id }}/delete/">删除</a>
                    <a class="btn btn-info btn-xs" href="/admin/{{ item.id }}/reset/">重置密码</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
</div>

{% endblock %}

mysite2/app01/templates/change.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <!-- Single button -->
        <div style="margin-bottom: 10px">
            <a class="btn btn-warning" href="/admin/add/" target="_blank">新建管理员</a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">{{ title }}</div>
            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                    <tr>
                        {% for field in form %}
                            <th>{{ field.label }}</th>
                        {% endfor %}
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    <form method="post" novalidate>
                    {% csrf_token %}
                        <tr>
                            {% for field in form %}
                                <td>{{ field }}</td>
                            {% endfor %}
                            <td><input type="submit" class="btn btn-warning btn-xs"></td>
                        </tr>
                        <tr>
                            {% for field in form %}
                                <td style="color: red">{{field.errors.0}}</td>
                            {% endfor %}
                        </tr>
                    </form>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

mysite2/app01/templates/city_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <!-- Single button -->
    <div class="clearfix" style="margin-bottom: 10px">
        <a class="btn btn-warning" href="/city/add/">
            新建城市</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">城市列表</div>
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>人口</th>
                <th>Logo</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
            <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.count }}</td>
                <td>
                <img src="/media/{{ item.img }}" style="height: 80px;">
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
</div>

{% endblock %}

mysite2/app01/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
        <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

mysite2/app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div style="margin-bottom: 10px">
        <input type="button" class="btn btn-info" value="新建订单1" data-toggle="modal" data-target="#myModal">
        <input type="button" id="btnAdd" class="btn btn-info" value="新建订单2(ajax)">
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">订单列表</div>
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>名称</th>
                <th>价格</th>
                <th>状态</th>
                <th>管理员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
            <tr uid="{{ item.id }}">
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.oid }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>{{ item.admin.username }}</td>
                <td>
                    <input uid="{{ item.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                    <input uid="{{ item.id }}" type="button" class="btn btn-danger btn-xs btn-delete" value="删除">
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
</div>
<!-- 新建 、编辑 对话框 -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">新 建</h4>
            </div>
            <div class="modal-body">
                <form id="formAdd">
                    <div class="clearfix">
                        {% for field in form %}
                        <div class="col-xs-6">
                            <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg" style="color: red;position: absolute;"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
            </div>
        </div>
    </div>
</div>
<!-- 删除 对话框 -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <h4>是否确定删除？</h4>
            <p style="margin: 10px 0;">yyy一月又一月晕晕晕晕晕晕晕</p>
            <p style="text-align: right;">
                <button id="btnConfirmDelete" type="button" class="btn btn-danger" >确 定</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                // 将正在编辑的ID设置为空 （undefined 作用未定义）
                EDIT_ID = undefined;
                $('#formAdd')[0].reset();
                $(".error-msg").empty();
                $('#myModalLabel').text('新建');
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                $(".error-msg").empty();
                if (EDIT_ID) {
                    // 编辑
                    doEdit();
                }else{
                    // 新建
                    doAdd();
                }

            })
        }
        function doEdit() {
            $.ajax({
                url:"/order/edit/" + "?uid=" + EDIT_ID,
                type:"post",
                data:$("#formAdd").serialize(),
                dataType:"JSON",
                success: function (res) {
                    if (res.status) {
                        // alert("创建成功");
                        // 清空表单 $("#formAdd")是jquery对象 $("#formAdd")[0] DOM对象
                        $("#formAdd")[0].reset();
                        // 关闭对话框
                        $('#myModal').modal('hide');
                        // 刷新页面
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips);
                        }else{
                            $.each(res.error, function (name, errorList) {
                                $("#id_"+name).next().text(errorList[0]);
                            })
                        }
                    }
                }
            })
        }
        function doAdd() {
            $.ajax({
                url:"/order/add/",
                type:"post",
                data:$("#formAdd").serialize(),
                dataType:"JSON",
                success: function (res) {
                    if (res.status) {
                        // alert("创建成功");
                        // 清空表单 $("#formAdd")是jquery对象 $("#formAdd")[0] DOM对象
                        $("#formAdd")[0].reset();
                        // 关闭对话框
                        $('#myModal').modal('hide');
                        // 刷新页面
                        location.reload();
                    } else {
                        $.each(res.error, function (name, errorList) {
                            $("#id_"+name).next().text(errorList[0]);
                        })
                    }
                }
            })
        }
        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function (){
                // alert("点击了删除");
                $("#deleteModal").modal("show");
                // 获取当前行的ID并赋值给全局变量。
                DELETE_ID = $(this).attr("uid");
            })
        }
        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                $.ajax({
                    url:"/order/delete/", // oooo/order/"+ DELETE_ID +"/delete/  => /order/123/delete/
                    type:"GET",
                    data:{
                        uid:DELETE_ID
                    },
                    dataType:"JSON",
                    success:function (res) {
                        if(res.status){
                            // $("#deleteModal").modal("hide");
                            // $("tr[uid='" + DELETE_ID + "']").remove();
                            DELETE_ID = 0;
                            location.reload();
                        }else{
                            alert(res.error);
                        }
                    }
                })
            })
        }
        function bindBtnEditEvent() {
            $(".btn-edit").click(function () {
                $("#formAdd")[0].reset();
                $(".error-msg").empty();
                var uid = $(this).attr("uid");
                EDIT_ID = uid;
                $.ajax({
                    url:"/order/detail/",
                    type:"get",
                    data:{
                        uid:uid
                    },
                    dataType:"JSON",
                    success: function (res) {
                        if (res.status) {
                            $.each(res.data, function (name, value) {
                                $("#id_"+name).val(value);
                            })
                            $("#myModalLabel").text("编辑");
                            $('#myModal').modal('show');
                        }else{
                            alert(res.error);
                        }
                    }
                })
            });
        }



</script>
{% endblock %}